### ISSUE TITLE
Recommendation: make lesson-core a separate repository

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-lesson-template#118]
Several people have said they find it confusing and error-prone to merge PRs into the `core` branch, then merge again into `gh-pages`. While this workflow seems OK for Git experts, it would be simpler for the majority to have a separate repository `lesson-core` as the upstream of `lesson-template`.

**Comment by abought** [comment]
As part of this move, I would suggest moving README.md, LAYOUT.md, and DESIGN.md to the `core` repository, rather than in `gh-pages`. These files are documentation, not lesson content.

This was part of the confusion for me: pull requests that change template behavior (build, validation etc) are split across two branches. One commit for code, another for documentation.

**Comment by ACharbonneau** [comment]
I think any sort of branching is inherently confusing when you first start in Git. I'm a bit past novice, but I still would have to sit and think about how to interact with this setup. Two repositories sounds much easier to think about.

**Comment by wking** [comment]
On Tue, Jan 13, 2015 at 08:38:24AM -0800, ACharbonneau wrote:

> I think any sort of branching is inherently confusing when you first
> start in Git. I'm a bit past novice, but I still would have to sit
> and think about how to interact with this setup. Two repositories
> sounds much easier to think about.

Out of curiosity, can you explain how your thought process is
different for two single-branch repositories vs. one two-branch
repository?

**Comment by willingc** [comment]
@gvwilson @wking Just my two cents...I understand git and I'm having a hard time following the overall logic flow of what the difference between core and gh-pages even if split into 2 repos. Since I jump in and out of this project, I'm not in tune with the details of what is trying to be accomplished by core vs gh-pages. So I rely on all the text documentation which is confusing not so much as individual documents but as the summary of what I should use and when.

A picture :sunrise:  might be worth a thousand words :smile:

Is there a visual (hand drawn is cool) of the following:
- What is on one's local computer (local), on user's github account (origin), and swcarpentry's account repo (upstream)? Perhaps laid out local(left), origin (middle), upstream (right side) on the visual.
- What is the flow for one using lesson-template/core?
- What is the flow for using lesson-template/gh-pages?
- When should I use core?
- When should I use gh-pages?

Whether a single repo with two branches or two repos, users will still need to understand what is going on before layering on the complexity of git commands.

**Comment by jdblischak** [comment]
I'd prefer not to have an additional repository to keep track of.

**Comment by wking** [comment]
On Wed, Jan 14, 2015 at 07:30:59PM -0800, John Blischak wrote:

> I'd prefer not to have an additional repository to keep track of.

I'm in favor of a single repository myself, but just to play Devil's
advocate:

You won't need to actually track the branch that's now
lesson-template's gh-pages if it ends up in a separate repository.
It's just the seed for new lessons.  Once you have a lesson, you only
need to track lesson-template's core branch.

**Comment by vahtras** [comment]
As a git intermediate (using basic git frequently) I can only agree with @willingc in that workflows can be very confusing and a graphical aid would help for any choice. What about having lesson-core as a git submodule of lesson-template?

**Comment by gvwilson** [comment]
Hi Olav,
Our experiences of git submodules were uniformly bad - there are too 
many ways for them to behave incomprehensibly in the hands of newcomers 
(including me).  Remember, the goal here isn't to find the "right" 
workflow for Git experts, but to find something that newcomers can drive 
reliably.
Thanks,
Greg

**Comment by aaren** [comment]
The biggest problem that I have with `core` is that it isn't documented anywhere that this is the branch to work on.

I'm undecided on which is better - two branches or two repos - for the core/gh-pages split.

**Comment by aaren** [comment]
I agree with @abought about moving readme, layout and design documentation.

**Comment by rgaiacs** [comment]
@willingc This is the way that I see the branches and pull requests.

![swc](https://cloud.githubusercontent.com/assets/1506457/5777536/996e1aee-9d7a-11e4-9924-2f33dc22930d.jpeg)

Hope this helps.

**Comment by jdblischak** [comment]
> I agree with @abought about moving readme, layout and design documentation.

But if the README is in core, consider the scenario where it gets updated. Then when I go to pull the latest changes in core into my lesson repository, won't this cause a merge conflict?

**Comment by aaren** [comment]
@jdblischak you're right (assuming you mean you've got your own separate readme) - I hadn't thought of this. You'd also get a copy of layout.md and design.md.

I'm not so sure about where the documentation should live anymore.

**Comment by jdblischak** [comment]
OK, then I am definintely opposed to including the README in core because it has to be updated in a lesson repo. From the beginning of [LAYOUT](https://raw.githubusercontent.com/swcarpentry/lesson-template/gh-pages/LAYOUT.md):
1.  `README.md`: initially a copy of this file.  It should be
   overwritten with short description of the lesson, but should
   include the following blockquote to help people find these
   instructions:
   
   ```
   > Please see [https://github.com/swcarpentry/lesson-template](https://github.com/swcarpentry/lesson-template)
   > for instructions on formatting, building, and submitting lessons,
   > or run `make` in this directory for a list of helpful commands.
   ```

I am indifferent to moving LAYOUT and DESIGN to core because a lesson repo does not need to update these files. Thus any changes made to them will safely merge when pulling from core.

**Comment by willingc** [comment]
@r-gaia-cs Thank you for taking the time to make a visual. I will take a look at the flow and process. I really appreciate the effort. I will get back with you once I get a chance to review :sunny:

**Comment by wking** [comment]
On Fri, Jan 16, 2015 at 06:25:15AM -0800, Raniere Silva wrote:

> This is the way that I see the branches and pull requests.

Is there source for this somewhere?  It needs an 'initial import'
arrow from gh-pages@lesson-template to gh-pages@shell-novice.

**Comment by wking** [comment]
On Fri, Jan 16, 2015 at 07:02:07AM -0800, John Blischak wrote:

> > I agree with @abought about moving readme, layout and design
> > documentation.
> 
> But if the README is in core, consider the scenario where it gets
> updated. Then why I go to pull the latest changes in core into my
> lesson repository, won't this cause a merge conflict?

To avoid this issue, I'd recommend keeping docs about the templates in
a subdirectory like doc/template/.  I'm testing this approach in #124.

**Comment by willingc** [comment]
I've had a chance to sit down and really dig into the workflow. At this point, I believe that the root issue is not one or two repos but better documentation of the git workflow when creating a remixed lesson.

I have had a chance to do a hand drawn visual of the process from the end user (writer of a remixed lesson) perspective. I did not include my messy drawing, but will redraw by hand if folks wish. It's essentially  4 columns (instruction step, local, user github and swc github repos) with each row contains the instruction step, local repo name and branches, origin remote repo name and branches, upstream remote repo name and branches). Arrows are used to demonstrate the flow of information in each step.

The keys to communicating a git workflow are sharing:
- clearly and consistently referring to local system and remote systems by remote names (local, origin, upstream)
- consistent use of repo names (local:user/lesson-name, github:user/lesson-name, github:swc/lesson-template)
- Initial state: Only github:swc/lesson-template exists
- Final state (after all steps completed): 3 repositories
- Repository states after each instruction step
- branch names need to be explicitly referenced
  -  On remote upstream swc/lesson-template: two branches are core [lesson content] and gh-pages [used to display to the web]
  -  On origin: gh-pages contains remixed lesson 
  -  On local: one branch gh-pages or two branches gh-pages  and remix [lesson content]

In addition to providing a git workflow visual, it can be helpful to give the users a way to check if their configuration is correct: git remote -v should be helpful here.

I also believe a guide or doc to explain how to fetch and rebase in upstream changes and how/when to create a pull request would help the user.

All that said, a visual would be the best addition.

**Comment by gvwilson** [comment]
Thanks very much for this, Carol.  Do you think a walkthrough screencast 
showing people the steps would help as well?  I've been promising one to 
@abostroem for months...

**Comment by wking** [comment]
On Sat, Jan 17, 2015 at 06:12:18AM -0800, Carol Willing wrote:

> - On remote upstream swc/lesson-template: two branches are core
>   [lesson content] and gh-pages [used to display to the web]

core is actually the lesson infrastructure (_layouts, _includes, css,
tools, Makefile, LICENSE.md, …), not the lesson content.  gh-pages has
example lesson-content that the lesson maintainer is supposed to
replace with real content for their particular lesson.

> -  On origin: gh-pages contains remixed lesson 
> -  On local: one branch gh-pages or two branches gh-pages and remix [lesson content]

Lesson maintainers should only have a single gh-pages branch (both in
their local copy and it's GitHub mirror), as Raniere shows in his
graphic [1](https://github.com/swcarpentry/lesson-template/issues/118#issuecomment-70260155).  The'll have a remote-tracking branch for
swc/lesson-template's core.  They may also have a remote-tracking
branch for swc/lesson-template's gh-pages, but that's only used for
the initial seed [2](https://github.com/swcarpentry/lesson-template/issues/118#issuecomment-70329173).

> In addition to providing a git workflow visual, …

I'd put this in doc/template (#124).

> … it can be helpful to
> give the users a way to check if their configuration is correct: git
> remote -v should be helpful here.
> 
> I also believe a guide or doc to explain how to fetch and rebase in
> upstream changes…

While this sort of thing is useful, I think basic Git workflow
information (checking your remote names, how to pull, merge, or
rebase, …) doesn't belong in this repository.  I think it belongs in
our intermediate Git lesson (swcarpentry/bc#929), where we can
centralize the material and avoid maintaining similar docs in each SWC
repository.

> … and how/when to create a pull request would help the user.

This would be specific to lesson-template, and I think we should have
those docs, likely in a doc/template/CONTRIBUTING.md in the core
branch, with a link from the root CONTRIBUTING.md (like the README.md
link I've setup in #124).  I'd keep the instructions high-level (like
Raniere's graphic) and not get into the weeds of the specific Git
commands to run.  Lesson maintainers familiar with intermediate Git
usage should (I think) be able to translate those into the appropriate
Git commits (with the right remote names, etc.) to execute the
workflow.  Does that sound workable?

**Comment by willingc** [comment]
@wking Please let me clarify...I used the instructions "as written" to come up with the comments that I made earlier. 

@gvwilson, @r-gaia-cs, @wking, @abostroem and others: 
Instead of addressing @wking's thoughtful comments inline, I want to stress that the instructions as written are confusing to someone that understands git and I expect would be to someone less experienced in git or the structure of the project.

I'm not saying the content or the process is wrong or bad. What I am saying is that there is room to iterate and improve the `Manual Setup` instructions as written to improve clarity for people that may not have an overview of what the different repositories and branches contain.

If there is another document somewhere that outlines the big picture or if the users of the `Manual Setup` instructions will have prior understanding of the repo structures, then I think the instructions are fine as written. 

I believe the content and use of a visual really comes down to the question of "who" the team expects to use the lesson-template and `manual setup` instructions.

**Comment by wking** [comment]
On Sat, Jan 17, 2015 at 10:21:11AM -0800, Carol Willing wrote:

> I'm not saying the content or the process is wrong or bad. What I am
> saying is that there is room to iterate and improve the `Manual
> Setup` instructions as written to improve clarity for people that
> may not have an overview of what the different repositories and
> branches contain.

I agree.  I was just trying to sketch out what I think the improved
instructions should (and should not) look like.  If it's easier to
review pull requests with improvements than it is to plan the
improvements abstractly, I'm happy to do that too.

> I believe the content and use of a visual really comes down to the
> question of "who" the team expects to use the lesson-template and
> `manual setup` instructions.

This is a good point.  The “Manual Setup” section is for folks
creating new downstream lessons (e.g. shell-novice).  We need
somewhere that explains to these downstream lesson maintainers that we
expect them to pull from core to stay up to date with the
lesson-template infrastructure.  We also need additional docs
(CONTRUBITING.md?) aimed at folks contributing to lesson-template
itself (likely there will be people who both contribute to
lesson-template and maintain downstream lessons).  I don't think we
have those docs yet, but Raniere's graphic is a good start [1](https://github.com/swcarpentry/lesson-template/issues/118#issuecomment-70260155).

**Comment by willingc** [comment]
@wking :bouquet: Cool with me.

I will defer to you and the group but my personal feeling that planning by Pull Request has the slippery slope of losing the big picture.

I agree that Raniere's graphic is a good starting point :) I will also post here an updated hand drawn graphic of my understanding basic on your additional comments. Heading out to teach today but will get to it over the long weekend.

Thanks for clarify who would be using the "Manual Setup" section. What sense do you have on their experience with git? Complete newcomer? Able to clone/push? Able to branch/set remotes? I'm just trying to get a sense of the git knowledge of the lesson writers. Totally cool if the answer is "across the board".

**Comment by wking** [comment]
On Sat, Jan 17, 2015 at 10:51:11AM -0800, Carol Willing wrote:

> Thanks for clarify who would be using the "Manual Setup"
> section. What sense do you have on their experience with git?
> Complete newcomer? Able to clone/push? Able to branch/set remotes?
> I'm just trying to get a sense of the git knowledge of the lesson
> writers. Totally cool if the answer is "across the board".

I expect that will be “we want this to be accessible to everyone,
including folks who haven't heard of Git”.  I'm just suggesting we
approach that by pointing newcomers to our novice Git material [1](http://swcarpentry.github.io/git-novice/) and
pointing novice Git users at our intermediate Git material
(swcarpentry/bc#929) instead of embedding all of that generic Git
training in our lesson-template docs.

**Comment by willingc** [comment]
@wking I agree that the instructions shouldn't teach git. What I would like "Manual Setup"  is expected action (commands) and expected result for a step so that users have a context of where they are in the setup process. Empower them to self troubleshoot their setup issues :)

**Comment by gvwilson** [comment]
> Instead of addressing @wking https://github.com/wking's thoughtful 
> comments inline, I want to stress that the instructions as written are 
> confusing to someone that understands git and I expect would be to 
> someone less experienced in git or the structure of the project.

I agree, and I"m grateful for your help in trying to find ways to 
explain this better.  I'm going to try to find time on Tuesday or 
Wednesday to rewrite the instructions using GitHub import instead of a 
manual import - may I ask you to proof-read?  (I'll include a diagram.)

**Comment by willingc** [comment]
Sure. Empower the users :)

Such great content in all of these lessons :)

**Comment by rgaiacs** [comment]
@gvwilson Can you create repositories for `core` and `gh-pages`? This will avoid trouble when people create pull requests. During the Easter I will try find some time to write a "how to" blog post to help people contributing to `core`.
