### ISSUE TITLE
Programmatically extract individual challenges into separate md files

### ISSUE THREAD

**Issue by strootman** [swcarpentry/DEPRECATED-lesson-template#120]
During a recent workshop, I manually broke out the challenges from several lessons into individual md files. 
This was very convenient to display only one challenge at a time. Also, I could display them from my own computer if the network went down

**Comment by jdblischak** [comment]
I have also extracted exercises manually in the past and wished it could be automated. Not only is this nice for displaying for the students, but I also like to compile all the challenges (and ideally their solutions as well) to give the helpers to prepare for the workshop.

**Comment by fmichonneau** [comment]
For data carpentry I used what I called a "skeleton" file that includes the
exercises and useful pieces of code. The file is generated automatically by
the make file using knitr::purl(). It's not perfect because the text for
the exercise is duplicated (once in the lesson and once as comments in the
R chunk) but the participants liked it.

**Comment by rgaiacs** [comment]
Thanks all for the feedbacks.

> This was very convenient to display only one challenge at a time. Also, I could display them from my own computer if the network went down

@strootman I like to wrote the challenges at the etherpad because (1) I can add extra challenges and (2) students can write their solutions if they want so. Unfortunately this isn't bullet proof across network problems.

> I also like to compile all the challenges (and ideally their solutions as well) to give the helpers to prepare for the workshop.

@jdblischak I believe that we can accomplish this using CSS. I'm working to get the all-in-one version of the lesson and will add your request to all-in-one version of challenges.

> For data carpentry I used what I called a "skeleton" file that includes the exercises and useful pieces of code.

Jekyll allows this "skeleton" model but many of our instructors complained when we try to use it, more information at https://github.com/swcarpentry/bc/issues/729.

**Comment by gvwilson** [comment]
@r-gaia-cs @abought progress on this?

**Comment by rgaiacs** [comment]
@gvwilson Nope. And I will only be available to work on this next month. =(

**Comment by fmichonneau** [comment]
If it helps @kbroman wrote a Ruby script that does that https://github.com/karawoo/2015-04-27-wsu/blob/gh-pages/syllabus/slides/grab_challenges.rb

**Comment by gvwilson** [comment]
Cool - I'll grab that.

**Comment by abought** [comment]
I'm going to build on the script from #247, with some filename handling improvements.

Is there any preference on filename / format conventions for the output? If people are doing anything special to render/display the individual challenge files, I can add post-processing to make this as convenient as possible for our instructors.

**Comment by gvwilson** [comment]
This one has gone stale, but will be revived once a new lesson format is agreed on - the new Kramdown tools for exporting an AST as JSON will help.
