### ISSUE TITLE
Checking tools should make sure the right Git remotes are set up

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-lesson-template#130]
The checking tool should check the Git remotes and make sure there's one pointing at `lesson-template` (or `lesson-core` if we decide to go that route).

**Comment by wking** [comment]
On Sun, Jan 18, 2015 at 02:02:11PM -0800, Greg Wilson wrote:

> The checking tool should check the Git remotes and make sure there's
> one pointing at `lesson-template` (or `lesson-core` if we decide to
> go that route).

Are you enforcing a particular name for that remote?

It's also possible to just:

  $ git pull git://github.com/swcarpentry/lesson-template core

and not have a named remote or tracking branches at all.  Is that an
unacceptable workflow?

This will also be hard to handle when we're running the check script
remotely, unless you mean a different check script than the one that's
been copied to amy (swcarpentry/amy#111), since folks are unlikely to
push their local .git/config to their public repository ;).

**Comment by gvwilson** [comment]
I'd like to enforce a particular name, even if it's not necessary - that 
way the documentation can refer to that name in examples.

**Comment by abought** [comment]
Do you prefer this be done by the lesson template validator, or a separate repository-setup script?

**Comment by gvwilson** [comment]
Not fussed about it being the same script or a different script as long 
as all checks are run by the same 'make' invocation.

**Comment by gvwilson** [comment]
@abought any chance to work on this?

**Comment by abought** [comment]
> @abought any chance to work on this?

This one fell off the radar. My initial instinct would be to check this every time it runs (for people pulling a pre-existing repository). I'll also take a look at how other pre-existing setup code (like the SWC installer) integrates with git tooling to see if there's any overlap.

**Comment by gvwilson** [comment]
Moved to https://github.com/swcarpentry/styles/issues/45 - please continue discussion there.
