### ISSUE TITLE
Add GitHub Ribbon

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/DEPRECATED-lesson-template#16]
Need to apply

```
diff --git a/_includes/banner.html b/_includes/banner.html
index 541ea7e..27266a2 100644
--- a/_includes/banner.html
+++ b/_includes/banner.html
@@ -1,3 +1,4 @@
+<span id="github-ribbon"><a href="https://github.com/swcarpentry/bc">Fork me on GitHub</a></span>
 <div class="banner">
   <a href="http://software-carpentry.org" title="Software Carpentry">
     <img alt="Software Carpentry banner" src="img/software-carpentry-banner.png" />
```

but with the correct value for href (i.e. not bc repo).

**Comment by gvwilson** [comment]
We want a "fork me on GitHub" ribbon on each lesson, and we want the URL to point to that lesson's repository.  The simplest solution is to include text like that above in `_layouts/page.html`, and have lesson authors edit it in place, but then each time authors update from `lesson-template/core` to get new layouts, CSS, etc., they'll have a merge conflict.  The other option is to add a `_config.yml` configuration file (which we've so far managed to avoid), and have them change the URL there, but that has the same problem with merge conflicts as the previous solution.  Is there a third option?

**Comment by wking** [comment]
On Tue, Dec 16, 2014 at 09:53:06AM -0800, Greg Wilson wrote:

> The simplest solution is to include text like that above in
> `_layouts/page.html`, and have lesson authors edit it in place, but
> then each time authors update from `lesson-template/core` to get new
> layouts, CSS, etc., they'll have a merge conflict.

Only if the core branch touches something near that line, but yes, it
would be nicer to have something with an even smaller cross-section.

> The other option is to add a `_config.yml` configuration file (which
> we've so far managed to avoid), and have them change the URL there,
> but that has the same problem with merge conflicts as the previous
> solution.

This sounds good to me.  I'd expect entries in _config.yml to be more
stable (and less likely to change in the upstream core branch) than
the markup that consumes the repository URL.

**Comment by swaldman3** [comment]
Another option, and the approach taken by one project I'm involved with: rather than having a config file in the core repo, have an _example_ config file in the core repo, and tell people when they are forking that they need to copy that example to the correct filename and fill in the appropriate details.

This avoids merge conflicts any time the config file changes in core, but does mean that if what needs to be in the config file - and hence the example one - changes significantly, people need to find out about it by some other means so as to update their own config file.

Pros & cons there.

**Comment by gvwilson** [comment]
@swaldman3 Interesting option - I think that has the advantage of 
deferring the merge, but not eliminating it: after I `git pull template 
core` to get the new content, I have to remember to manually merge any 
changes from the demo config file into my copy of the config file.
Thanks,
Greg

**Comment by wking** [comment]
On Wed, Dec 17, 2014 at 01:45:02AM -0800, Simon wrote:

> Another option, and the approach taken by one project I'm involved
> with: rather than having a config file in the core repo, have an
> _example_ config file in the core repo, and tell people when they
> are forking that they need to copy that example to the correct
> filename and fill in the appropriate details.
> 
> This avoids merge conflicts any time the config file changes in
> core, but does mean that if what needs to be in the config file

I'm not sure what the threshold is, but if you don't make many changes
Git may follow the file through the rename:

  mkdir a &&
  (cd a &&
    git init &&
    cat > example_config.yml <<-EOF &&
    url: http://example.com/
    name: my lesson
    version: 0.1.0
    EOF
    git add example_config.yml &&
    git commit -m 'Initial example_config.yml'
  ) &&
  git clone a b &&
  (cd b &&
    git mv example_config.yml _config.yml &&
    sed -i 's|http://example.com/|http://example.com/my-lesson/|' _config.yml &&
    git commit -am 'Update our URL'
  ) &&
  (cd a &&
    sed -i 's|my lesson|our lesson|' example_config.yml &&
    git commit -am 'Update our example name'
  ) &&
  (cd b &&
    git pull origin master
  )

I just ran this with Git 2.1.0, and the final merge raised:

  CONFLICT (modify/delete): example_config.yml deleted in HEAD and
    modified in 26c77f4175dc8eb9e169d570eb5a0c769ce2cffe. Version
    26c77f4175dc8eb9e169d570eb5a0c769ce2cffe of example_config.yml
    left in tree.
  Automatic merge failed; fix conflicts and then commit the result.

because Git didn't recognize the rename (the URL line is too high a
fraction of the total file).  However, running the same sequence with:

  git pull -Xrename-threshold=20 origin master

raises:

  Auto-merging _config.yml
  CONFLICT (content): Merge conflict in _config.yml
  Recorded preimage for '_config.yml'
  Automatic merge failed; fix conflicts and then commit the result.

so Git is recognizing the rename if we lower the threshold.  To avoid
conflicts entirely you'll have to leave example_config.yml in the
lesson repository, replacing:

  git mv example_config.yml _config.yml &&

with

  cp example_config.yml _config.yml &&
  git add _config.yml &&

because there doesn't seem to be a merge-option equivalent to diff's
--find-copies.
