### ISSUE TITLE
Should we allow sub-headings within lessons?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-lesson-template#220]
See the thread starting at http://lists.software-carpentry.org/pipermail/discuss_lists.software-carpentry.org/2015-April/002920.html for background - should we permit sub-sections within topic pages in lessons, or should we stick to the rule that "if you want to break it into pieces, you should start a fresh page"?

**Comment by wking** [comment]
On Sun, Apr 05, 2015 at 05:37:11AM -0700, Greg Wilson wrote:

> … should we permit sub-sections within topic pages in lessons, or
> should we stick to the rule that "if you want to break it into
> pieces, you should start a fresh page"?

I it's a good idea to break to a new topic file instead of adding
intra-topic headers, but I'd also like to leave these sorts of minor
details to the discretion of the lesson's maintainer.  So “suggest no
intra-topic headers, but don't test for them in the validation
scripts”.

**Comment by DamienIrving** [comment]
I like @wking's suggestion of leaving these types of small details to the discretion of the author. Perhaps the language used by `make check` could just be scaled back a little? Instead of:  
_The topic page should not have sub-headings outside of special blocks. If a topic needs sub-headings, it should be broken into multiple topics._  
it could say something along the lines of:  
_Your page makes use of sub-headings. If appropriate, please consider breaking your lesson into smaller sections rather than using sub-headings._  

The "if appropriate" is important here, because there are many cases where the use of sub-headings is not a good indicator of a lesson break point (I'd argue that challenges are a better break point indicator). At one point in [this lesson](http://damienirving.github.io/capstone-oceanography/03-data-provenance.html), for example, I say that I'm going to generate three things: a time stamp, a command line record and a git hash. I then proceed to have a sub-heading for each of these. The content under each sub-heading is only 10 or so lines long, so I certainly don't want to be breaking into three separate sections. The sub headings are simply there to enhance the readability of the notes. Similarly, the sub-headings were recently removed from the [analyzing patient data](http://swcarpentry.github.io/python-novice-inflammation/01-numpy.html) python lesson and I think that has significantly detracted from the readability of that lesson.

**Comment by rgaiacs** [comment]
I added this as blocking Version 5.3.

@jiffyclub Can you or the Lesson Development Subcommittee take a decision on this so that I can make the last changes on `tools/check.py` and we can all work to have no errors/warnings on the lessons?

**Comment by jiffyclub** [comment]
What was the rationale behind not allowing sub-headings in lessons? Is it only that we want to discourage long lessons, or was there another reason?

**Comment by DamienIrving** [comment]
@jiffyclub As far as I'm aware it was just to discourage long lessons. The rationale goes that anytime you use a sub-heading you should start a new lesson instead. 

As I say above, I think discouraging sub-headings is compromising the readability of our lesson notes (and readability is actually very important when you're standing up in front of a class frantically checking your notes to remember what to teach next - headings really help with fast scanning of the notes). 

A more natural break point in the lessons (if you did want to make them shorter) would be whenever a challenge comes up. That would result in a lot of individual lessons (e.g. [analyzing patient data](http://swcarpentry.github.io/python-novice-inflammation/01-numpy.html) would probably become 3 separate lessons) but would actually make for a nice flow during the class. You'd teach for 10-15 minutes and then say, "go to the lesson webpage and do all the challenges." At the moment you get about a third of the way through the analyzing patient data lesson and then have to tell people to go to the lesson webpage do the first couple of challenges listed at the bottom of the page but not all of them. As it stands it's also not clear where during the lesson those challenges should happen. Splitting lessons at challenge points would remove this ambiguity. (Of course, an alternative would be to place challenges in the lesson notes where they occur as opposed to all at the end, which was the original approach before the lesson template existed - that would avoid the need to break analyzing patient data into 3 parts, even though all three cover essentially the same topic).

**Comment by DamienIrving** [comment]
If it were me I'd vote for allowing sub headings and the placement of challenges where they occur (i.e. I don't think there was anything wrong with what we were doing before the lesson template existed). That gives the lesson author some flexibility to make their lessons as readable as possible (via the use of subheadings) and also flexibility in teaching style. If they want to teach a particular concept via a challenge as opposed to live coding, they can go ahead and pop a challenge into the notes at that point.

We can encourage authors to break up their lessons into separate files as much as possible, but by imposing artificial rules on subheadings and challenge placement I think we are ultimately making our lessons worse.

**Comment by wking** [comment]
On Mon, Apr 27, 2015 at 01:46:39PM -0700, Damien Irving wrote:

> … that would avoid the need to break analyzing patient data into 3
> parts, even though all three cover essentially the same topic).

I haven't looked over this lesson recently, but if there are three
essentially similar parts wrapped around the excercises, I think
splitting those up into separate topics would help everybody focus on
what the distinctions are.  It's good to keep everyone focused on what
the new thing is that you're learning since the last exercise.

**Comment by wking** [comment]
On Mon, Apr 27, 2015 at 01:52:45PM -0700, Damien Irving wrote:

> We can encourage authors to break up their lessons into separate
> files as much as possible, but by imposing artificial rules on
> subheadings and challenge placement I think we are ultimately making
> our lessons worse.

+1 to author choice with guidance on best-practices.  If the author
ignores best-practices where they would help, they probably shouldn't
be the maintainer of a core lesson.  And if someone wants to go rogue
on a peripheral lesson, then I don't think we really care strongly
enough to hound them about it :p.

**Comment by DamienIrving** [comment]
They are essentially similar in the sense that they are all concerned with the quick initial task of reading in data and plotting it (i.e. they are very strongly related to one another and follow directly from one another). In three parts they are "variable assignment", "indexing" and "plotting", which could be demarcated via sub-headings or separate lessons. Each have challenges relating to them.

**Comment by abought** [comment]
> +1 to author choice with guidance on best-practices.

Agreed. The "no subheadings within lessons" rule was always subject to revisiting, and someone will always find a good way to take advantage of the capability. In practice, I found that banning subheadings completely generated a lot of errors in stable lessons to little benefit.

In this case, the proposed change is to `tools/check.py` (TopicPageValidator). Currently it errors if ANY headings are present inside the document. After the change, headings would be allowed: a warning message would still be printed, but validation would not fail outright. Currently, it only allows heading nodes that are inside blockquoted elements. (eg challenge boxes are already ok)

I have internet access again, and will work on getting back up to speed.

**Comment by gvwilson** [comment]
I still think that if you want sub-headings, you probably want to break 
the file into pieces, and that if there are challenges you want to use 
in the middle of a lesson, you _definitely_ want to break it into pieces.

**Comment by wking** [comment]
On Tue, Apr 28, 2015 at 03:13:38AM -0700, Greg Wilson wrote:

> I still think that if you want sub-headings, you probably want to
> break the file into pieces, and that if there are challenges you
> want to use in the middle of a lesson, you _definitely_ want to
> break it into pieces.

I agree with you, but don't feel strongly enough about it to want to
unlist a lesson if it's maintainers don't agree ;).

**Comment by tbekolay** [comment]
While ideologically I agree with the idea that subheadings shouldn't be necessary in any topic, I think that this doesn't match reality. I was going through the Python novice lesson to fix these issues, and it really doesn't seem like splitting [09-errors](http://swcarpentry.github.io/python-novice-inflammation/09-errors.html) into separate pages makes sense, and removing the subheadings hurts readability.

So, I think I agree with the general theme of this thread that this is something worth questioning, but not something that should be an "error" per se. Two possible ways forward are (IMHO):
1. Make the subheadings check a WARNING rather than an ERROR (and make it possible to run `check.py` with/without seeing WARNINGs, e.g. with a `--strict` flag).
2. Make it possible to declare a subheading as unavoidable. In Python, you can add a `# noqa` comment to lines that violate a style guide, but for a good reason; we can use a similar HTML comment, or CSS class, or something like that.

**Comment by wking** [comment]
On Mon, May 04, 2015 at 08:25:32AM -0700, Trevor Bekolay wrote:

> 1. Make the subheadings check a WARNING rather than an ERROR (and
>    make it possible to run `check.py` with/without seeing WARNINGs,
>    e.g. with a `--strict` flag).

This sounds like log levels to me ;).  How about:

  --log-level {critical|error|warning|info|debug}

that sets the checker's log level?

> 1. Make it possible to declare a subheading as unavoidable. In
>    Python, you can add a `# noqa` comment to lines that violate a style
>    guide, but for a good reason; we can use a similar HTML comment, or
>    CSS class, or something like that.

This sounds too intrusive to me, but I'll accept it if it ends up
being the consensus approach.

**Comment by tbekolay** [comment]
> This sounds like log levels to me ;).  How about:
> --log-level {critical|error|warning|info|debug}
> 
> that sets the checker's log level?

It's does sound like log levels, but it's a style checker, so the fact that it emits log messages with levels seems like an implementation detail to me. I got `--strict` from [Homebrew's `audit` script](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/cmd/audit.rb#L11).

Not that I'm entirely opposed to using `--log-level`, it just seems like A) you would rarely want to use a level other than error or warning, and B) `--log-level` isn't an intuitive command line argument to `tools/check.py` in my mind.

**Comment by jiffyclub** [comment]
I'd personally do something very explicit like `--hide-warnings`.

**Comment by wking** [comment]
On Mon, May 04, 2015 at 09:50:47AM -0700, Matt Davis wrote:

> I'd personally do something very explicit like `--hide-warnings`.

My main concern with boolean options is that we'd have to add more if
we wanted to add additional levels later.  Maybe we're ok running that
risk though…

**Comment by jiffyclub** [comment]
I think @r-gaia-cs, @gvwilson, and I came to the agreement that we'll allow sub-headings in lessons and convert the errors in the check tool into warnings.

**Comment by gvwilson** [comment]
Resolution is to allow sub-headings.
