### ISSUE TITLE
Add the current maintainers' contact info to the CONTRIBUTING.md.

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-lesson-template#262]
Or have a lesson-name@software-carpentry.org mail forwarder for each lesson?

**Comment by wking** [comment]
I have trouble imagining feedback folks would want to send maintainers
that wouldn't be appropriate for a GitHub issue.

And the current maintainer listing is in README.md [1](https://github.com/swcarpentry/lesson-template/issues/195#issuecomment-89643048), so that's
where I'd suggest putting any additional maintainer information if we
do want to add it.

**Comment by gdevenyi** [comment]
-1 for contacts other than github. I'd like to keep my communications confined to as few mediums as possible.

**Comment by abought** [comment]
Interesting idea, but I'd like to see a few use cases first. Agree with @wking that public github issues would offer more context and accountability.

If we do want an email contact route, my preference would be for the group address, to ensure a fast response from whoever of the group was free.
