### ISSUE TITLE
Modify build process to turn Jupyter Notebooks into Markdown with trailing styles

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-lesson-template#278]
In order to convert from Pandoc to Jekyll, we need our build process to generate plain old Markdown with trailing style specifications:

```
> ## title
> body
{: .style}
```

and similarly for code.

**Comment by aaren** [comment]
I could probably add a `swc` flag to [notedown](https://github.com/aaren/notedown) that generates the appropriate markdown from a notebook.

Something like

```
notedown lesson.ipynb --to markdown --swc > lesson.md
```

Then call it from the Makefile similar to how Rscript is called now.

You then have a notedown dependency, but it's a single `pip install` away. Thoughts?

**Comment by rgaiacs** [comment]
@aaren Based on http://lists.software-carpentry.org/pipermail/discuss_lists.software-carpentry.org/2015-June/003127.html, can you wait a few days before start working on this?

You can restore the workflow from https://github.com/swcarpentry/bc/. Take a look at https://github.com/swcarpentry/bc/blob/gh-pages/Makefile for understand the workflow and make changes at https://github.com/swcarpentry/bc/blob/gh-pages/_templates/ipynb.tpl.

I'm OK using notedown but people prefer to use nbconvert just because it works out of the box.

**Comment by aaren** [comment]
@r-gaia-cs good point! I'd forgotten that notebook-> markdown was easy with nbconvert - that's a better solution. (notedown's main value is markdown -> notebook).

**Comment by gvwilson** [comment]
Moved to https://github.com/swcarpentry/styles/issues/53
