### ISSUE TITLE
Rendering LaTeX equations in R Markdown files

### ISSUE THREAD

**Issue by jdblischak** [swcarpentry/DEPRECATED-lesson-template#285]
One nice feature of R Markdown is that it will render LaTeX equations ([syntax](http://rmarkdown.rstudio.com/authoring_basics.html)). We have a [PR](https://github.com/swcarpentry/r-novice-inflammation/pull/154) from @michaellevy to [r-novice-inflammation](https://github.com/swcarpentry/r-novice-inflammation) which includes a demonstration of this feature. However, the equation does not render properly when using our pandoc-based workflow. Would it be possible to update this to accommodate this feature?

When converting Markdown to HTML, the [rmarkdown](http://rmarkdown.rstudio.com) package uses the following pandoc flags:

```
 --to html
 --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures
 --output 07-knitr-R.html
 --smart
 --email-obfuscation none
 --self-contained
 --standalone
 --section-divs
 --template /usr/lib/R/site-library/rmarkdown/rmd/h/default.html
 --variable 'theme:bootstrap'
 --include-in-header /tmp/RtmpgXmbe8/rmarkdown-strdb9256d2983.html
 --mathjax
 --variable 'mathjax-url:https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML'
 --no-highlight
 --variable highlightjs=/usr/lib/R/site-library/rmarkdown/rmd/h/highlight 
```

I tried updating the pandoc args in the lesson-template Makefile to include the flags that are likely involved in facilitating this, but it didn't work:

```
PANDOC_FLAGS = --smart --mathjax --variable 'mathjax-url:https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures
```

**Comment by gvwilson** [comment]
+1 if someone smarter than me can figure out the Pandoc flags.

**Comment by cboettig** [comment]
@jdblischak  Well, notice that RStudio has pandoc using `--template /usr/lib/R/site-library/rmarkdown/rmd/h/default.html` .

Meahwhile, you seem to be constructing a rather different template with `_layout/page.html` and some `-Vheader` etc stuff from `_includes`.

Note that you won't just be able modify `_includes/header.html` directly from Pandoc/rmarkdown's default.html, because it that uses variables and you can't have variables in header snippets in pandoc (only in template files).  

But all that makes this sound more complicated than it is.  To fix. just add `--mathjax` flag to your PANDOC_FLAGS and add:

```
    <script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
```

to your `_includes/header.html` and you should be good to go (does assume an internet connection is available for the javascript, but you get the idea)

**Comment by rgaiacs** [comment]
@jdblischak Thanks for create the issue.

This is related with https://github.com/swcarpentry/lesson-template/issues/121.

**Comment by rgaiacs** [comment]
@jdblischak and @michaellevy Could you check https://github.com/swcarpentry/lesson-example/pull/15 and let me know if is OK? If yes, I will merge https://github.com/swcarpentry/lesson-template/pull/286 and https://github.com/swcarpentry/lesson-example/pull/15.

**Comment by jdblischak** [comment]
> This is related with #121.

OK. Good to know there is general support for this. Sorry for the extra Issue. I searched the Issues for the term "equation", and surprisingly that word is never used in #121.

> Could you check swcarpentry/lesson-example#15 and let me know if is OK? If yes, I will merge #286 and swcarpentry/lesson-example#15.

I did a test merge of your PR #286 and it properly renders the equation. +1 to merge into lesson-template.

I didn't actually test your PR to lesson-example, but from a quick glance it looks reasonable, too.
