### ISSUE TITLE
Improve tools/check to be compatible with id at glossary entries

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/DEPRECATED-lesson-template#46]
After apply #44 and

```
diff --git a/pages/01-one.md b/pages/01-one.md
index ca4dc26..c00fce8 100644
--- a/pages/01-one.md
+++ b/pages/01-one.md
@@ -9,7 +9,8 @@ minutes: 10
 > * Learning objective 1
 > * Learning objective 2

-Paragraphs of text --- possibly including **definitions** ---
+Paragraphs of text
+--- possibly including [definitions](reference.html#key-word-1) ---
 mixed with:

 ~~~ {.python}
diff --git a/pages/02-two.md b/pages/02-two.md
index 0412d1b..4b969a8 100644
--- a/pages/02-two.md
+++ b/pages/02-two.md
@@ -9,7 +9,8 @@ minutes: 10
 > * Learning objective 1
 > * Learning objective 2

-Paragraphs of text --- possibly including **definitions** ---
+Paragraphs of text
+--- possibly including [definitions](reference.html#key-word-1) ---
 mixed with:

 ~~~ {.python}
```

`tools/check` will give some errors:

```
$ python tools/check pages 
ERROR:root:In pages/01-one.md: The linked page reference.html#key-word-1 exists, but the link text 'definitions' does not match the (sub)title of that page, 'Reference'.
ERROR:root:In pages/02-two.md: The linked page reference.html#key-word-1 exists, but the link text 'definitions' does not match the (sub)title of that page, 'Reference'.
WARNING:root:Some errors were encountered during validation. See log for details.
```

`tools/check` need to be updated to cover this case.

**Comment by abought** [comment]
Anchor links are actually ignored; in initial testing they had no effect on the link validation. Though I agree that the first half of the error message could be clearer about that.

This error message happens when the text of the link is different than the `subtitle` YAML header of the linked document.

A link as follows... `possibly including [definitions](reference.html#key-word-1)`) will check this part of reference.md:
 `subtitle: Reference`

@r-gaia-cs Let me know when the change to directory organization is merged; I'll update the checker to clarify the error message and deal with #45 at the same time. Let me know if you'd prefer further resolution on this issue as well.

**Comment by rgaiacs** [comment]
@PBarmby Thanks very much for the work with the glossary in all the lessons (https://github.com/swcarpentry/python-novice-inflammation/pull/3, https://github.com/swcarpentry/shell-novice/pull/37, https://github.com/swcarpentry/hg-novice/pull/1, https://github.com/swcarpentry/sql-novice-survey/pull/10, https://github.com/swcarpentry/git-novice/pull/6). I will do my best to have a pull request for this issue and get it merge as soon as possible.

**Comment by gvwilson** [comment]
Is this still live?

**Comment by rgaiacs** [comment]
> Is this still live?

@gvwilson you can close and I will create another issue/pull request when I back to work on this.
