### ISSUE TITLE
Should we generate HTML pages for the gh-pages branch?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-lesson-template#53]
Should this repo have a website with generated HTML versions of the dummy pages?

**Comment by jrsmith3** [comment]
What's the downside?

**Comment by wking** [comment]
On Fri, Dec 12, 2014 at 02:50:19AM -0800, Greg Wilson wrote:

> Should this repo have a website with generated HTML versions of the
> dummy pages?

I think yes.  It's always good to dogfood your own framework when
possible.

**Comment by gvwilson** [comment]
Closed by 142672a

**Comment by wking** [comment]
On Fri, Dec 12, 2014 at 05:41:06PM -0800, Greg Wilson wrote:

> Closed by 142672a

I'd have a separate ‘example’ branch that didn't include the
auto-generated content though [1,2].

**Comment by gvwilson** [comment]
But a separate `example` branch wouldn't model what our authors do: they 
have HTML and source in the `gh-pages` branch.

**Comment by wking** [comment]
On Sat, Dec 13, 2014 at 09:36:25AM -0800, Greg Wilson wrote:

> But a separate `example` branch wouldn't model what our authors do:
> they have HTML and source in the `gh-pages` branch.

I see two levels to this:
- Should the lack of separation between source and compiled output be
  part of the official workflow?  This is debatable, with
  version-control best practices pushing for separation, and simpler
  Git usage pushing for a single branch.  I'm fine if the consensus
  decision is for a single ‘gh-pages’ branch that contains both the
  source and compiled HTML.
- Should a separation between the source and compiled output be
  _possible_ for folks who prefer it (and don't mind the additional
  branch).  I think so.

My solution would be to have a source-only ‘example’ branch, which
gets compiled into the gh-pages branch.  Folks consuming
lesson-template don't need to care about the example branch if they
don't want to; they can just clone from gh-pages (and post-clone pulls
and merges will be from the ‘core’ branch anyway).

The lesson-template maintainers are likely comfortable enough with Git
to manage the additional branch easily, and if they aren't it would be
easy to bring them up to speed.  I'd probably try to talk lesson
maintainers into preserving this separation too, because it is easier
to review changes if you don't have the distraction of parallel
changes to the compiled content cluttering your commits, or the worry
that the source and compiled versions might be going out of sync.
Once you get to a per-workshop repository it doesn't matter as much,
because you're on a dead-end branch that's not intended for future
development.

Pull requests against gh-pages would be easy to review as they're
posted, and the maintainers coud rebase them onto the example branch
when merging, so I'm not worried about an additional barrier for
contributions from non-Git users.
