### ISSUE TITLE
ALL tests of validator fail

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/DEPRECATED-lesson-template#54]
This happens due #48.

```
$ git log HEAD -1
commit 3eaab252ad43a066d016390b8e70449efe212208
Author: Greg Wilson <gvwilson@third-bit.com>
Date:   Thu Dec 11 20:29:12 2014 -0500

    Removing example files (they belong in the gh-pages branch)
$ cd tools
$ python test_check.py 2>&1 | tail
  File "test_check.py", line 20, in setUp
    self.sample_validator = self.VALIDATOR(self.SAMPLE_FILE)
  File "check", line 63, in __init__
    with open(filename, 'rU') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/raniere/software-carpentry/lesson-template/01-one.md'

----------------------------------------------------------------------
Ran 37 tests in 0.038s

FAILED (errors=35)
```

The tests depend on the Markdown examples.

**Comment by rgaiacs** [comment]
@abought Do you have a suggestion to fix this?

**Comment by abought** [comment]
The failure of tests is because they reference specific example files that no longer live on the `core` branch. 

When I checked out branch `gh-pages`, all tests passed without problems. Are the files on gh-pages insufficient for some reason? If so, let me know what the desired use case is, and I'll be happy to implement a fix.

I do think there's value in having the validator check our actual example files where possible; if we instead embedded the markdown in the tests, it would be harder to keep up to date when the example files changed.

**Comment by gvwilson** [comment]
For now, we can tell people that the validator only runs in the gh-pages 
branch of lesson-template (where the example files are).

**Comment by abought** [comment]
@gvwilson , this discussion is about the _unit tests_. I can't think of any reason why lessons themselves would fail to validate. 

To confirm, I copied the example markdown files (and nothing else) to the `core` branch. The validator itself worked fine.

`tools/check` works fine.
`tools/test_check.py` depends on example files.

**Comment by gvwilson** [comment]
My apologies - wasn't reading carefully enough.

**Comment by rgaiacs** [comment]
> I do think there's value in having the validator check our actual example
> files where possible; if we instead embedded the markdown in the tests, it
> would be harder to keep up to date when the example files changed. 

I'm +1 to embedded the Markdown in the tests. This will allow
-   Run the test at the core branch
-   Run the test at the gh-pages branch
-   Run the test at others repositories

I agree that embedded the Markdown in the tests will make harder to keep it up
to date when the examples files changed but I see it in a positive way since it
will look like test driver development.

**Comment by abought** [comment]
I have created a pull request to `core` with a proposed fix that I think balances both of our concerns, as follows. What do you think?
- Testing actual example assets is a functional test, not a unit test. We should not embed markdown, because then the functional tests would give a false sense of security. (Functional tests exist to ensure that the validation matches the specification, as laid out in the most recent example files.)
- The real problem is that a failure in the functional tests prevents everything else from running. I agree with @r-gaia-cs completely here: individual unit tests should be more independent.
- The solution is to move the sample file validation out of the `setUp()` function. With this change, only 11 filesystem-dependent functional tests fail. (instead of all 37 defined tests)

Since individual lesson authors should not modify the validator, I think it's ok to have certain tests that only run on `gh-pages`. Presumably, all validator development should be confined to the lesson-template repo.

Also, question for @gvwilson : which branch (`core` or `gh-pages`) should I submit pull requests to? Is there a procedure for automatically merging changes into both branches?

**Comment by rgaiacs** [comment]
@abought Thanks a lot for the pull request.
I will review it at the end of the week.

> which branch (`core` or `gh-pages`) should I submit pull requests to?
- CSS, Javascript, validator files should go first to `core`
- Markdown examples should go only to `gh-pages`.

**Comment by abought** [comment]
Have you had a chance to review this pull request yet? I know this is a blocker for other pull requests right now.

**Comment by rgaiacs** [comment]
> Have you had a chance to review this pull request yet?

Sorry for the delay.

The fact that functional test doesn't pass on `core` branch is still bugging me. Unfortunately I didn't find a good solution. To avoid ["development hell"](https://en.wikipedia.org/wiki/Development_hell) I merged @abought pull request and will close this issue for now. If you have any suggestion, please open a issue or send a pull request.
