### ISSUE TITLE
Build process gives wrong results if reference.md subtitle changes

### ISSUE THREAD

**Issue by abought** [swcarpentry/DEPRECATED-lesson-template#77]
Side comment extracted from #74 for tracking.

When the YAML header "subtitle" in `reference.md` is changed, the page builds differently. (glossary entries are not wrapped in span tags correctly).

This is because the build process hard-codes an assumption that the subtitle will be "Reference". (tools/filters/id4glossary.py, line 27) 

This has implications for lesson creators: their page will not build correctly if the document subtitle is changed, and not everyone will want to call the page "Reference". (especially when building translations) Should we change the build process, or enforce the subtitle by adding a check to the validator?

A sample change to the validator is provided below.

```
@@ -417,7 +417,7 @@ class ReferencePageValidator(MarkdownValidator):

     DOC_HEADERS = {"layout": vh.is_str,
                    "title": vh.is_str,
-                   "subtitle": vh.is_str}
+                   "subtitle": lambda t: t == "Reference2"}
```

**Comment by gvwilson** [comment]
The other option is to create some other page layouts with hard-coded 
subtitles, then pick up the title from _config.yml --- I'm increasingly 
resigned to having to have a config file, because we want links to the 
lesson's repo in the page footers.  See 
https://github.com/swcarpentry/workshop-template which now has a 
_config.yml.

**Comment by rgaiacs** [comment]
I'm closing this one since #81 was merged.
