### ISSUE TITLE
Pandoc "not found in path" error

### ISSUE THREAD

**Issue by shwina** [swcarpentry/DEPRECATED-lesson-template#83]
Not sure if this has been documented, but when I first ran `make preview`, I got an error about the filter `tools/filters/blockquote2div.py` "not found in path".

As it turns out, that's a useless error message. It's thrown if the filter can't execute for _any_ reason. This bug has been documented here, under the section 'Behaviour changes':

http://johnmacfarlane.net/pandoc/releases.html

The real problem was that I didn't have `pandocfilters` installed, so `tools/filters/blockquote2div.py` couldn't execute. The fix was simply to install it:

`pip install pandocfilters`

Hope this helps, and sorry for the noise if it's irrelevant :)

**Comment by rgaiacs** [comment]
@ashwinsrnth Thanks very much for your report. I'm closing this since the need to install `pandocfilters` is already mentioned on `README.md`, check the "Dependencies" section, due cf51ae0.

We all are working hard to get the new lesson stable as soon as possible to avoid this type of problem.

> Hope this helps, and sorry for the noise if it's irrelevant :)

Please, report as many issues as problems that you have. We will try to solve it as quickly as possible.

**Comment by shwina** [comment]
Thanks!

**Comment by gvwilson** [comment]
Please add this one to the FAQ - other people will run into it, and help 
diagnosing problems is always welcome.
