### ISSUE TITLE
HTML files adding noise to version control?

### ISSUE THREAD

**Issue by shwina** [swcarpentry/DEPRECATED-lesson-template#87]
Should `.html` files be part of the lesson repo? It seems to me that they simply make version control noisy. Can someone point out the advantages? Thanks!

**Comment by gvwilson** [comment]
See point 6 in lesson-template's DESIGN.md (rendered version at 
http://swcarpentry.github.io/lesson-template/DESIGN.html).

**Comment by wking** [comment]
On Sun, Dec 21, 2014 at 02:27:11AM -0800, Greg Wilson wrote:

> See point 6 in lesson-template's DESIGN.md (rendered version at 
> http://swcarpentry.github.io/lesson-template/DESIGN.html).

Point 6 doesn't address committing the HTML to the development branch.
It's argument is:
- “HTML pages … must be committed to version control in order for the
  lesson to be displayed properly on GitHub.” (which is true)
- “We [put generated files in the same directory as source files]
  because some authors may use auxiliary source files such as R
  Markdown and IPython Notebook files which are executable, and
  contain paths to things like images and data files. If we put our
  source files in a sub-directory, those paths won't work (or
  conversely, if we put our generated files in a different directory,
  the paths won't work there).” (which is true, but irrelevant to the
  version control).

The unstated requirement is (I think):
- lesson-template maintainers aren't savvy enough Git users to handle
  developing the content in a ‘master’ branch and building and
  deploying it in a ‘gh-pages’ branch.

I disagree with the unstated requirement.  Even if it was true now
(which I doubt), it would be a matter of hours to get the
lesson-template maintainers up to speed on such a workflow, and the
more experienced Git users in our community are always available if
anyone wants some follow-up advice.  I think that having development
with human-generated content in ‘master’ with occasional merges into
‘gh-pages’ for compilation and release would be a net benefit in terms
of maintainer time (time lost in any additional training would be
regained through easier pull reviews and the avoidance of fix-up PRs
like #84).

**Comment by gvwilson** [comment]
You've brought this up many times, Trevor - please let it go.

**Comment by wking** [comment]
On Sun, Dec 21, 2014 at 11:03:52AM -0800, Greg Wilson wrote:

> You've brought this up many times, Trevor - please let it go.

I won't bring it up on my own, but I'll mention my support and
reasoning when other folks bring it up.  Maybe like swcarpentry/bc#102
it will be something that takes a year to gain traction, but I think
that it _is_ the right choice, and the current “just gh-pages”
approach makes it impossible for folks who don't like auto-generated
content in the development branch to use that approach either here or
in any downstream repository.  I'd rather avoid another
history-extraction phase if/when we come around on this, which I
expect we will sooner or later.  The alternative to a
history-extraction phase would be to leave the auto-generated content
in the old history which clutters the history and makes it harder to
focus on the human-generated changes when we look back at this history
in the future (e.g. when deciding whether an issue we're thinking
about was considered when the text we're thinking about was originally
written).  On the other hand, collapsing from a “both master and
gh-pages” workflow here to a “just gh-pages” workflow in downstream
repositories is really easy.

Given those potential issues with the “just gh-pages” approach and the
ease of accommodating gh-pages-only consumers with either approach, I
think it's worth making sure that avoiding a human-generated
development branch is a concious decision.  Especially since I'm not
clear on why we're resisting the change; I have my guess [1](https://github.com/swcarpentry/lesson-template/issues/87#issuecomment-67774707), but I
don't think that argument holds water, and I don't think we've
explicitly discussed it.

**Comment by shwina** [comment]
I'll add that I'm with @wking on this. If there has already been discussion about this, I'd be interested to read it
